# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsFeedApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsFeedApp
  pod 'SwiftLint'                                     # A tool to enforce Swift style and conventions. https://realm.io
  pod 'R.swift'
  pod 'IQKeyboardManager'

  target 'NewsFeedAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsFeedAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
